server:
  port: 1020
spring:
  application:
    name: 'demo-rabbitmq-consumer'
  #    配置rabbitmq
  rabbitmq:
    host: 192.168.159.128
    port: 5672
    username: guest
    password: guest
    queueName: demo
    exchangeName: demoExchange
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.128:8848
