server:
  port: 5050
  shutdown: graceful
spring:
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.159.128:3306/dockertest?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: 'demo-home'
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# swagger3的配置
swagger3:
  enable: true
  application-name: ${spring.application.name}
  application-version: 'V1.1'
  application-description: 'swagger3.1整合Demo'
  try-host: http://localhost:${server.port}