server:
  port: 6666
  shutdown: graceful
spring:
#  MySQL
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.159.128:3307/dockertest?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: 'demo-home'
#    redis配置
  redis:
    port: 6379
    host: 192.168.159.128
  security:
    user:
      name: admin
      password: admin
  cloud:
    nacos:
      discovery:
#        springcloudAlibaba nacos注册中心配置
        server-addr: 192.168.159.128:8848
#    服务监控设置
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# swagger3的配置
swagger3:
  enable: true
  application-name: ${spring.application.name}
  application-version: 'V1.1'
  application-description: 'swagger3.1整合Demo'
  try-host: http://localhost:${server.port}
#  mybatisplus全局配置
mybatis-plus:
  global-config:
    db-config:
#      id自增
      id-type: auto
#      表名使用驼峰
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

